version: "3"

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=movie_db
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=testpasswd
    volumes:
      - db_data:/var/lib/mysql

  django_db:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
     - ./database/database/.env
    ports:
      - "3000:3000"
    volumes:
      - static_volume:/app/static
    depends_on:
      - db

volumes:
  db_data:
  static_volume:
