# Generated by Django 3.1.7 on 2021-04-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=60)),
                ('actors', models.TextField(max_length=512)),
                ('genre', models.CharField(max_length=40)),
                ('release_date', models.DateField()),
                ('rating', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'movies',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('password', models.TextField(max_length=512)),
                ('date_registered', models.DateTimeField(verbose_name='date registered')),
            ],
            options={
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.user')),
                ('movies_added', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'managers',
            },
            bases=('posts.user',),
        ),
        migrations.CreateModel(
            name='viewer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.user')),
                ('movies_viewed', models.BigIntegerField()),
                ('movies_rated', models.BigIntegerField()),
                ('movies_loved', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'viewers',
            },
            bases=('posts.user',),
        ),
    ]
