# Generated by Django 3.1.7 on 2021-06-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_who', models.CharField(max_length=60)),
                ('subject', models.TextField(max_length=200)),
                ('message', models.TextField(max_length=1024)),
                ('to_whom', models.CharField(max_length=60)),
                ('date_sent', models.DateTimeField(verbose_name='date sent')),
            ],
            options={
                'verbose_name_plural': 'emails',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=60)),
                ('actors', models.TextField(max_length=512)),
                ('genre', models.CharField(max_length=40)),
                ('release_date', models.DateField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'verbose_name_plural': 'movies',
            },
        ),
    ]
