# Generated by Django 3.1.7 on 2021-04-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_who', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=1024)),
                ('to_whom', models.CharField(max_length=60)),
                ('date_sent', models.DateTimeField(verbose_name='date sent')),
            ],
        ),
    ]
