# Generated by Django 3.1.7 on 2021-04-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name_plural': 'emails'},
        ),
    ]
