# Generated by Django 3.1.7 on 2021-04-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210427_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.TextField(max_length=200),
        ),
    ]
