apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-db
spec:
  replicas: 1
  selector:
    matchLabels:
      component: django-db
  template:
    metadata:
      labels:
        component: django-db
    spec:
      #initContainers:
      #  - name: django-init
      #    image: bel_panos/movie-db
      #    command: ["/bin/bash"]
      #    args: ["-c", "python manage.py makemigrations && python manage.py migrate"]
      containers:
        - name: django-db
          image: bel_panos/movie-db:latest
          #- auth:
          #   username:
          #    valueFrom:
          #      secretKeyRef:
          #        name: docker-creds
          #        key: DOCKERUSER
          #   password:
          #    valueFrom:
          #      secretKeyRef:
          #        name: docker-creds
          #        key: DOCKERPASSWORD
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: django-db-config
          imagePullPolicy: Always
